# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
module "label" {
  # v0.25.0
  source = "github.com/cloudposse/terraform-null-label?ref=488ab91e34a24a86957e397d9f7262ec5925586a"

  namespace   = "jmgilman"
  environment = "kiada"
  stage       = local.env
  name        = local.name
}
