# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  # State information
  region = "us-west-2"
  bucket = "jmgilman-kiada-example"
  lock = "jmgilman-kiada-example"

  # Local module name and environment
  name = basename(abspath("${path.module}"))
  env = basename(abspath("${path.module}/.."))
}
