# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "jmgilman-kiada-example"
    dynamodb_table = "jmgilman-kiada-example"
    encrypt        = true
    key            = "dev/network/terraform.tfstate"
    region         = "us-west-2"
  }
}
