kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Configure to use calico
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 # Calico's default subnet

# Configure a multi-node cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
